language: objective-c
osx_image: xcode9.2

install:
  - brew tap wix/brew
  - brew install --HEAD applesimutils
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install
  - nvm use
  - npm install -g react-native-cli
  - npm install -g detox-cli
  - npm install

script:
  - npm test
  - detox build --configuration ios.sim.debug
  - detox test --configuration ios.sim.debug --cleanup
